# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nickj\Desktop\ZZZ\g9.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot
import socket
from threading import Thread
import time


def client_thread(g9_c, ui_arg):
    g9_c.start_client(ui_arg)

class g9Client():

    def start_client(self, ui_arg):
        hostname, sld, tld, port = 'www', 'theberrics', 'com', 80
        target = '{}.{}.{}'.format(hostname, sld, tld)
        
        # create an ipv4 (AF_INET) socket object using the tcp protocol (SOCK_STREAM)
        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        
        # connect the client
        # client.connect((target, port))
        client.connect(('127.0.0.1', 1256))
        # client.connect(('10.56.31.170', 1256))
        # client.connect(('192.168.1.129', 1256))
        # client.connect(('10.56.30.250', 1256))
        print('connected:\n')
        
        # ------------------- FOR WEB ADDRESSES  ----------------------------------------
        # addr_str = 'GET /index.html HTTP/1.1\r\nHost: {}.{}\r\n\r\n'.format(sld, tld)
        # encoded_str = addr_str.encode()
        
        server_msg = client.recv(1024)
        
        print('past received\n')
        
        print(server_msg)
        
        # msg = '&&&& CLIENT &&&&&&&&\n'
        # client.send(msg.encode())        
        # send some data (in this case a HTTP GET request)

        byte0 = (0).to_bytes(1, byteorder = 'big') # 0  
        byte1 = (0).to_bytes(1, byteorder = 'big') # 1
        byte2 = (0).to_bytes(1, byteorder = 'big') # 2
        byte3 = (0).to_bytes(1, byteorder = 'big') # 3
        byte4 = (0).to_bytes(1, byteorder = 'big') # 4
        byte5 = (0).to_bytes(1, byteorder = 'big') # 5
        byte6 = (0).to_bytes(1, byteorder = 'big') # 6
        byte7 = (0).to_bytes(1, byteorder = 'big') # 7
        byte8 = (0).to_bytes(1, byteorder = 'big') # 8
        byte9 = (0).to_bytes(1, byteorder = 'big') # 9
        byte10 = (0).to_bytes(1, byteorder = 'big') # 10
        byte11 = (0).to_bytes(1, byteorder = 'big') # 11
        byte12 = (0).to_bytes(1, byteorder = 'big') # 12


        while True:
    
            time.sleep(1)

            msg2 = str(ui_arg.input_slid.value()) + '\t' + str(ui_arg.output_slid.value()) + '\t' + str(ui_arg.lo_slid.value()) + '\t' + str(ui_arg.mid_slid.value()) + '\t' + str(ui_arg.hi_slid.value()) + '\t' + str(ui_arg.treb_slid.value()) + '\t' + str(ui_arg.lo_freq_slid.value())  + '\t' +  str(ui_arg.mid_freq_slid.value()) + '\t' + str(ui_arg.hi_freq_slid.value())  + '\t' + str(ui_arg.cmp_slid1.value())  + '\t' +  str(ui_arg.cmp_slid2.value())  + '\t' +  str(ui_arg.rev_slid1.value())  + '\t' +  str(ui_arg.rev_slid2.value())
    
            #byte1 = ui_arg.verticalSlider.value().to_bytes(1, byteorder = 'big')
            #byte2 = ui_arg.verticalSlider_2.value().to_bytes(1, byteorder = 'big')
            #byte3 = ui_arg.verticalSlider_3.value().to_bytes(1, byteorder = 'big')

            byte0 = ui_arg.input_slid.value().to_bytes(1, byteorder = 'big')
            byte1 = ui_arg.output_slid.value().to_bytes(1, byteorder = 'big')
            byte2 = ui_arg.lo_slid.value().to_bytes(1, byteorder = 'big')            
            byte3 = ui_arg.mid_slid.value().to_bytes(1, byteorder = 'big')
            byte4 = ui_arg.hi_slid.value().to_bytes(1, byteorder = 'big')
            byte5 = ui_arg.treb_slid.value().to_bytes(1, byteorder = 'big')
            byte6 = ui_arg.lo_freq_slid.value().to_bytes(1, byteorder = 'big')
            byte7 = ui_arg.mid_freq_slid.value().to_bytes(1, byteorder = 'big')
            byte8 = ui_arg.hi_freq_slid.value().to_bytes(1, byteorder = 'big')
            byte9 = ui_arg.cmp_slid1.value().to_bytes(1, byteorder = 'big')
            byte10 = ui_arg.cmp_slid2.value().to_bytes(1, byteorder = 'big')
            byte11 = ui_arg.rev_slid1.value().to_bytes(1, byteorder = 'big')
            byte12 = ui_arg.rev_slid2.value().to_bytes(1, byteorder = 'big')


            client.send(byte0)
            client.send(byte1)
            client.send(byte2)
            client.send(byte3)
            client.send(byte4)
            client.send(byte5)
            client.send(byte6)
            client.send(byte7)
            client.send(byte8)
            client.send(byte9)
            client.send(byte10)
            client.send(byte11)
            client.send(byte12)            


            print(msg2 + '\r')
        
        # receive the response data (4096 is recommended buffer size)
        response = client.recv(4096)
        
        print(response)


class Ui_TabWidget(object):

    # ADDED DATA MEMBERS
    inpt = 50           # 0
    outpt = 50          # 1
    lo = 50             # 2
    mid = 50            # 3
    hi = 50             # 4
    treb = 50           # 5
    lo_freq = 50        # 6
    mid_freq = 50       # 7
    hi_freq = 50        # 8
    cmp_slid1 = 50      # 9
    cmp_slid2 = 50      # 10
    rev_slid1 = 50      # 11
    rev_slid2 = 50      # 12


    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(2456, 1718)
        TabWidget.setMinimumSize(QtCore.QSize(1600, 1600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 29, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        TabWidget.setPalette(palette)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(400, 400))
        self.label_10.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("Montroc")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.input_slid = QtWidgets.QSlider(self.tab)
        self.input_slid.setOrientation(QtCore.Qt.Vertical)
        self.input_slid.setObjectName("input_slid")
        self.horizontalLayout_12.addWidget(self.input_slid)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.input_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_lcd.sizePolicy().hasHeightForWidth())
        self.input_lcd.setSizePolicy(sizePolicy)
        self.input_lcd.setMinimumSize(QtCore.QSize(0, 40))
        self.input_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.input_lcd.setObjectName("input_lcd")
        self.horizontalLayout_37.addWidget(self.input_lcd)
        self.verticalLayout.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.input_field = QtWidgets.QLineEdit(self.tab)
        self.input_field.setObjectName("input_field")
        self.horizontalLayout_38.addWidget(self.input_field)
        self.verticalLayout.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_36.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.output_slid = QtWidgets.QSlider(self.tab)
        self.output_slid.setOrientation(QtCore.Qt.Vertical)
        self.output_slid.setObjectName("output_slid")
        self.horizontalLayout_40.addWidget(self.output_slid)
        self.verticalLayout_3.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.output_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_lcd.sizePolicy().hasHeightForWidth())
        self.output_lcd.setSizePolicy(sizePolicy)
        self.output_lcd.setMinimumSize(QtCore.QSize(0, 40))
        self.output_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.output_lcd.setObjectName("output_lcd")
        self.horizontalLayout_39.addWidget(self.output_lcd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.output_field = QtWidgets.QLineEdit(self.tab)
        self.output_field.setObjectName("output_field")
        self.horizontalLayout_41.addWidget(self.output_field)
        self.verticalLayout_3.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_42.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(400, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(800, 16777215))
        self.pushButton.setBaseSize(QtCore.QSize(400, 0))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setMinimumSize(QtCore.QSize(60, 0))
        self.line_10.setLineWidth(3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_2.addWidget(self.line_10)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_5.addWidget(self.line_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lo_slid = QtWidgets.QSlider(self.tab)
        self.lo_slid.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lo_slid.sizePolicy().hasHeightForWidth())
        self.lo_slid.setSizePolicy(sizePolicy)
        self.lo_slid.setMinimumSize(QtCore.QSize(60, 400))
        self.lo_slid.setMaximumSize(QtCore.QSize(16777215, 1300))
        self.lo_slid.setOrientation(QtCore.Qt.Vertical)
        self.lo_slid.setObjectName("lo_slid")
        self.horizontalLayout_6.addWidget(self.lo_slid)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lo_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lo_lcd.sizePolicy().hasHeightForWidth())
        self.lo_lcd.setSizePolicy(sizePolicy)
        self.lo_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.lo_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lo_lcd.setObjectName("lo_lcd")
        self.horizontalLayout_26.addWidget(self.lo_lcd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.lo_field = QtWidgets.QLineEdit(self.tab)
        self.lo_field.setMinimumSize(QtCore.QSize(150, 0))
        self.lo_field.setObjectName("lo_field")
        self.horizontalLayout_31.addWidget(self.lo_field)
        self.verticalLayout_5.addLayout(self.horizontalLayout_31)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.lo_freq_slid = QtWidgets.QSlider(self.tab)
        self.lo_freq_slid.setMinimumSize(QtCore.QSize(350, 40))
        self.lo_freq_slid.setOrientation(QtCore.Qt.Horizontal)
        self.lo_freq_slid.setObjectName("lo_freq_slid")
        self.verticalLayout_5.addWidget(self.lo_freq_slid)
        self.lo_freq_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lo_freq_lcd.sizePolicy().hasHeightForWidth())
        self.lo_freq_lcd.setSizePolicy(sizePolicy)
        self.lo_freq_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.lo_freq_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lo_freq_lcd.setObjectName("lo_freq_lcd")
        self.verticalLayout_5.addWidget(self.lo_freq_lcd)
        self.lo_freq_field = QtWidgets.QLineEdit(self.tab)
        self.lo_freq_field.setMinimumSize(QtCore.QSize(150, 0))
        self.lo_freq_field.setObjectName("lo_freq_field")
        self.verticalLayout_5.addWidget(self.lo_freq_field)
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_12 = QtWidgets.QFrame(self.tab)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_6.addWidget(self.line_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mid_slid = QtWidgets.QSlider(self.tab)
        self.mid_slid.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_slid.sizePolicy().hasHeightForWidth())
        self.mid_slid.setSizePolicy(sizePolicy)
        self.mid_slid.setMinimumSize(QtCore.QSize(60, 400))
        self.mid_slid.setMaximumSize(QtCore.QSize(16777215, 1300))
        self.mid_slid.setOrientation(QtCore.Qt.Vertical)
        self.mid_slid.setObjectName("mid_slid")
        self.horizontalLayout_7.addWidget(self.mid_slid)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.mid_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_lcd.sizePolicy().hasHeightForWidth())
        self.mid_lcd.setSizePolicy(sizePolicy)
        self.mid_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.mid_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.mid_lcd.setObjectName("mid_lcd")
        self.horizontalLayout_27.addWidget(self.mid_lcd)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.mid_field = QtWidgets.QLineEdit(self.tab)
        self.mid_field.setMinimumSize(QtCore.QSize(150, 0))
        self.mid_field.setObjectName("mid_field")
        self.horizontalLayout_29.addWidget(self.mid_field)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.mid_freq_slid = QtWidgets.QSlider(self.tab)
        self.mid_freq_slid.setMinimumSize(QtCore.QSize(350, 40))
        self.mid_freq_slid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mid_freq_slid.setOrientation(QtCore.Qt.Horizontal)
        self.mid_freq_slid.setObjectName("mid_freq_slid")
        self.verticalLayout_6.addWidget(self.mid_freq_slid)
        self.mid_freq_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_freq_lcd.sizePolicy().hasHeightForWidth())
        self.mid_freq_lcd.setSizePolicy(sizePolicy)
        self.mid_freq_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.mid_freq_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.mid_freq_lcd.setObjectName("mid_freq_lcd")
        self.verticalLayout_6.addWidget(self.mid_freq_lcd)
        self.mid_freq_field = QtWidgets.QLineEdit(self.tab)
        self.mid_freq_field.setMinimumSize(QtCore.QSize(150, 0))
        self.mid_freq_field.setObjectName("mid_freq_field")
        self.verticalLayout_6.addWidget(self.mid_freq_field)
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_6.addWidget(self.line_7)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_13 = QtWidgets.QFrame(self.tab)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_7.addWidget(self.line_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.hi_slid = QtWidgets.QSlider(self.tab)
        self.hi_slid.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hi_slid.sizePolicy().hasHeightForWidth())
        self.hi_slid.setSizePolicy(sizePolicy)
        self.hi_slid.setMinimumSize(QtCore.QSize(60, 400))
        self.hi_slid.setMaximumSize(QtCore.QSize(16777215, 1300))
        self.hi_slid.setOrientation(QtCore.Qt.Vertical)
        self.hi_slid.setObjectName("hi_slid")
        self.horizontalLayout_10.addWidget(self.hi_slid)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.hi_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hi_lcd.sizePolicy().hasHeightForWidth())
        self.hi_lcd.setSizePolicy(sizePolicy)
        self.hi_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.hi_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.hi_lcd.setObjectName("hi_lcd")
        self.horizontalLayout_28.addWidget(self.hi_lcd)
        self.verticalLayout_7.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.hi_field = QtWidgets.QLineEdit(self.tab)
        self.hi_field.setMinimumSize(QtCore.QSize(150, 0))
        self.hi_field.setObjectName("hi_field")
        self.horizontalLayout_30.addWidget(self.hi_field)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.hi_freq_slid = QtWidgets.QSlider(self.tab)
        self.hi_freq_slid.setMinimumSize(QtCore.QSize(350, 40))
        self.hi_freq_slid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.hi_freq_slid.setOrientation(QtCore.Qt.Horizontal)
        self.hi_freq_slid.setObjectName("hi_freq_slid")
        self.verticalLayout_7.addWidget(self.hi_freq_slid)
        self.hi_freq_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hi_freq_lcd.sizePolicy().hasHeightForWidth())
        self.hi_freq_lcd.setSizePolicy(sizePolicy)
        self.hi_freq_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.hi_freq_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.hi_freq_lcd.setObjectName("hi_freq_lcd")
        self.verticalLayout_7.addWidget(self.hi_freq_lcd)
        self.hi_freq_field = QtWidgets.QLineEdit(self.tab)
        self.hi_freq_field.setMinimumSize(QtCore.QSize(150, 0))
        self.hi_freq_field.setObjectName("hi_freq_field")
        self.verticalLayout_7.addWidget(self.hi_freq_field)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_7.addWidget(self.line_8)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.line_15 = QtWidgets.QFrame(self.tab)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_10.addWidget(self.line_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.treb_slid = QtWidgets.QSlider(self.tab)
        self.treb_slid.setMinimumSize(QtCore.QSize(60, 0))
        self.treb_slid.setOrientation(QtCore.Qt.Vertical)
        self.treb_slid.setObjectName("treb_slid")
        self.horizontalLayout_32.addWidget(self.treb_slid)
        self.verticalLayout_11.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.treb_lcd = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treb_lcd.sizePolicy().hasHeightForWidth())
        self.treb_lcd.setSizePolicy(sizePolicy)
        self.treb_lcd.setMinimumSize(QtCore.QSize(150, 80))
        self.treb_lcd.setMaximumSize(QtCore.QSize(16777215, 80))
        self.treb_lcd.setObjectName("treb_lcd")
        self.horizontalLayout_33.addWidget(self.treb_lcd)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.treb_field = QtWidgets.QLineEdit(self.tab)
        self.treb_field.setMinimumSize(QtCore.QSize(350, 0))
        self.treb_field.setObjectName("treb_field")
        self.horizontalLayout_35.addWidget(self.treb_field)
        self.verticalLayout_10.addLayout(self.horizontalLayout_35)
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 243, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(10, -1, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(400, 400))
        self.label_14.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("Montroc")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.input_slid_2 = QtWidgets.QSlider(self.tab1)
        self.input_slid_2.setOrientation(QtCore.Qt.Vertical)
        self.input_slid_2.setObjectName("input_slid_2")
        self.horizontalLayout_17.addWidget(self.input_slid_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.input_lcd_2 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_lcd_2.sizePolicy().hasHeightForWidth())
        self.input_lcd_2.setSizePolicy(sizePolicy)
        self.input_lcd_2.setMinimumSize(QtCore.QSize(350, 40))
        self.input_lcd_2.setMaximumSize(QtCore.QSize(350, 40))
        self.input_lcd_2.setObjectName("input_lcd_2")
        self.horizontalLayout_49.addWidget(self.input_lcd_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.input_field2 = QtWidgets.QLineEdit(self.tab1)
        self.input_field2.setMinimumSize(QtCore.QSize(350, 0))
        self.input_field2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.input_field2.setObjectName("input_field2")
        self.horizontalLayout_47.addWidget(self.input_field2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_15 = QtWidgets.QLabel(self.tab1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_45.addWidget(self.label_15)
        self.verticalLayout_12.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.output_slid_2 = QtWidgets.QSlider(self.tab1)
        self.output_slid_2.setOrientation(QtCore.Qt.Vertical)
        self.output_slid_2.setObjectName("output_slid_2")
        self.horizontalLayout_44.addWidget(self.output_slid_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.output_lcd_2 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_lcd_2.sizePolicy().hasHeightForWidth())
        self.output_lcd_2.setSizePolicy(sizePolicy)
        self.output_lcd_2.setMinimumSize(QtCore.QSize(350, 40))
        self.output_lcd_2.setMaximumSize(QtCore.QSize(350, 40))
        self.output_lcd_2.setObjectName("output_lcd_2")
        self.horizontalLayout_50.addWidget(self.output_lcd_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.output_field2 = QtWidgets.QLineEdit(self.tab1)
        self.output_field2.setMinimumSize(QtCore.QSize(350, 0))
        self.output_field2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.output_field2.setObjectName("output_field2")
        self.horizontalLayout_48.addWidget(self.output_field2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_16 = QtWidgets.QLabel(self.tab1)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_46.addWidget(self.label_16)
        self.verticalLayout_14.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(700, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_9.addWidget(self.pushButton_3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_9)
        self.line_19 = QtWidgets.QFrame(self.tab1)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_18.addWidget(self.line_19)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.line_20 = QtWidgets.QFrame(self.tab1)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_27.addWidget(self.line_20)
        self.label_17 = QtWidgets.QLabel(self.tab1)
        self.label_17.setMinimumSize(QtCore.QSize(600, 40))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_27.addWidget(self.label_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.cmp_slid1 = QtWidgets.QSlider(self.tab1)
        self.cmp_slid1.setOrientation(QtCore.Qt.Vertical)
        self.cmp_slid1.setObjectName("cmp_slid1")
        self.horizontalLayout_21.addWidget(self.cmp_slid1)
        self.verticalLayout_29.addLayout(self.horizontalLayout_21)
        self.cmp_lcd1 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmp_lcd1.sizePolicy().hasHeightForWidth())
        self.cmp_lcd1.setSizePolicy(sizePolicy)
        self.cmp_lcd1.setMinimumSize(QtCore.QSize(350, 80))
        self.cmp_lcd1.setMaximumSize(QtCore.QSize(3000, 80))
        self.cmp_lcd1.setObjectName("cmp_lcd1")
        self.verticalLayout_29.addWidget(self.cmp_lcd1)
        self.cmp_field1 = QtWidgets.QLineEdit(self.tab1)
        self.cmp_field1.setObjectName("cmp_field1")
        self.verticalLayout_29.addWidget(self.cmp_field1)
        self.label_19 = QtWidgets.QLabel(self.tab1)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_29.addWidget(self.label_19)
        self.horizontalLayout_19.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.cmp_slid2 = QtWidgets.QSlider(self.tab1)
        self.cmp_slid2.setOrientation(QtCore.Qt.Vertical)
        self.cmp_slid2.setObjectName("cmp_slid2")
        self.horizontalLayout_22.addWidget(self.cmp_slid2)
        self.verticalLayout_30.addLayout(self.horizontalLayout_22)
        self.cmp_lcd2 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmp_lcd2.sizePolicy().hasHeightForWidth())
        self.cmp_lcd2.setSizePolicy(sizePolicy)
        self.cmp_lcd2.setMinimumSize(QtCore.QSize(350, 80))
        self.cmp_lcd2.setMaximumSize(QtCore.QSize(3000, 80))
        self.cmp_lcd2.setObjectName("cmp_lcd2")
        self.verticalLayout_30.addWidget(self.cmp_lcd2)
        self.cmp_field2 = QtWidgets.QLineEdit(self.tab1)
        self.cmp_field2.setObjectName("cmp_field2")
        self.verticalLayout_30.addWidget(self.cmp_field2)
        self.label_20 = QtWidgets.QLabel(self.tab1)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_30.addWidget(self.label_20)
        self.horizontalLayout_19.addLayout(self.verticalLayout_30)
        self.verticalLayout_27.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18.addLayout(self.verticalLayout_27)
        self.line_21 = QtWidgets.QFrame(self.tab1)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_18.addWidget(self.line_21)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.line_22 = QtWidgets.QFrame(self.tab1)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_28.addWidget(self.line_22)
        self.label_18 = QtWidgets.QLabel(self.tab1)
        self.label_18.setMinimumSize(QtCore.QSize(600, 40))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_28.addWidget(self.label_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.rev_slid1 = QtWidgets.QSlider(self.tab1)
        self.rev_slid1.setOrientation(QtCore.Qt.Vertical)
        self.rev_slid1.setObjectName("rev_slid1")
        self.horizontalLayout_23.addWidget(self.rev_slid1)
        self.verticalLayout_31.addLayout(self.horizontalLayout_23)
        self.rev_lcd1 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rev_lcd1.sizePolicy().hasHeightForWidth())
        self.rev_lcd1.setSizePolicy(sizePolicy)
        self.rev_lcd1.setMinimumSize(QtCore.QSize(350, 80))
        self.rev_lcd1.setMaximumSize(QtCore.QSize(3000, 80))
        self.rev_lcd1.setObjectName("rev_lcd1")
        self.verticalLayout_31.addWidget(self.rev_lcd1)
        self.rev_field1 = QtWidgets.QLineEdit(self.tab1)
        self.rev_field1.setObjectName("rev_field1")
        self.verticalLayout_31.addWidget(self.rev_field1)
        self.label_21 = QtWidgets.QLabel(self.tab1)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_31.addWidget(self.label_21)
        self.horizontalLayout_20.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.rev_slid2 = QtWidgets.QSlider(self.tab1)
        self.rev_slid2.setOrientation(QtCore.Qt.Vertical)
        self.rev_slid2.setObjectName("rev_slid2")
        self.horizontalLayout_24.addWidget(self.rev_slid2)
        self.verticalLayout_32.addLayout(self.horizontalLayout_24)
        self.rev_lcd2 = QtWidgets.QLCDNumber(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rev_lcd2.sizePolicy().hasHeightForWidth())
        self.rev_lcd2.setSizePolicy(sizePolicy)
        self.rev_lcd2.setMinimumSize(QtCore.QSize(350, 80))
        self.rev_lcd2.setMaximumSize(QtCore.QSize(3000, 80))
        self.rev_lcd2.setObjectName("rev_lcd2")
        self.verticalLayout_32.addWidget(self.rev_lcd2)
        self.rev_field2 = QtWidgets.QLineEdit(self.tab1)
        self.rev_field2.setObjectName("rev_field2")
        self.verticalLayout_32.addWidget(self.rev_field2)
        self.label_22 = QtWidgets.QLabel(self.tab1)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_32.addWidget(self.label_22)
        self.horizontalLayout_20.addLayout(self.verticalLayout_32)
        self.verticalLayout_28.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18.addLayout(self.verticalLayout_28)
        self.line_23 = QtWidgets.QFrame(self.tab1)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_18.addWidget(self.line_23)
        TabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        TabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        self.output_slid.valueChanged['int'].connect(self.output_lcd.display)
        self.lo_slid.valueChanged['int'].connect(self.lo_lcd.display)
        self.mid_slid.valueChanged['int'].connect(self.mid_lcd.display)
        self.hi_slid.valueChanged['int'].connect(self.hi_lcd.display)
        self.treb_slid.valueChanged['int'].connect(self.treb_lcd.display)
        self.lo_freq_slid.valueChanged['int'].connect(self.lo_freq_lcd.display)
        self.mid_freq_slid.valueChanged['int'].connect(self.mid_freq_lcd.display)
        self.hi_freq_slid.valueChanged['int'].connect(self.hi_freq_lcd.display)
        self.input_slid.valueChanged['int'].connect(self.input_lcd.display)
        self.input_slid_2.valueChanged['int'].connect(self.input_lcd_2.display)
        self.output_slid_2.valueChanged['int'].connect(self.output_lcd_2.display)
        self.cmp_slid1.valueChanged['int'].connect(self.cmp_lcd1.display)
        self.cmp_slid2.valueChanged['int'].connect(self.cmp_lcd2.display)
        self.rev_slid1.valueChanged['int'].connect(self.rev_lcd1.display)
        self.rev_slid2.valueChanged['int'].connect(self.rev_lcd2.display)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "G9 PROCESSOR"))
        self.label_10.setText(_translate("TabWidget", "G9"))
        self.label_5.setText(_translate("TabWidget", "INPUT"))
        self.label_6.setText(_translate("TabWidget", "OUTPUT"))
        self.pushButton.setText(_translate("TabWidget", "CONNECT"))
        self.label.setText(_translate("TabWidget", "LO"))
        self.label_7.setText(_translate("TabWidget", "LO FREQ"))
        self.label_2.setText(_translate("TabWidget", "MID"))
        self.label_8.setText(_translate("TabWidget", "MID FREQ"))
        self.label_3.setText(_translate("TabWidget", "HI"))
        self.label_9.setText(_translate("TabWidget", "HI FREQ"))
        self.label_4.setText(_translate("TabWidget", "TREB"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "EQUALIZER"))
        self.label_14.setText(_translate("TabWidget", "G9"))
        self.label_15.setText(_translate("TabWidget", "INPUT"))
        self.label_16.setText(_translate("TabWidget", "OUTPUT"))
        self.pushButton_3.setText(_translate("TabWidget", "CONNECT"))
        self.label_17.setText(_translate("TabWidget", "COMPRESSOR"))
        self.label_19.setText(_translate("TabWidget", "COMP A"))
        self.label_20.setText(_translate("TabWidget", "COMP B"))
        self.label_18.setText(_translate("TabWidget", "REVERB"))
        self.label_21.setText(_translate("TabWidget", "REVERB A"))
        self.label_22.setText(_translate("TabWidget", "REVERB B"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "COMPRESSOR/REVERB"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "ALL"))

    # @pyqtSlot(int, name='on_verticalSlider_sliderMoved')
    # def on_verticalSlider_sliderMoved(self, i):
    #     lo = i
    #     print("LO: " + str(lo))        

    # @pyqtSlot(int, name='on_verticalSlider_2_sliderMoved')
    # def on_verticalSlider_2_sliderMoved(self, i):
    #     mid = i
    #     print("LO: " + str(mid))

    # @pyqtSlot(int, name='on_verticalSlider_3_sliderMoved')
    # def on_verticalSlider_3_sliderMoved(self, i):
    #     hi = i
    #     print("LO: " + str(hi))

    @pyqtSlot(int, name='on_lo_slid_sliderMoved')
    def on_lo_slid_sliderMoved(self, i):    
        lo = i
        print("LO: " + str(lo))    

    @pyqtSlot(int, name='on_mid_slid_sliderMoved')
    def on_mid_slid_sliderMoved(self, i):    
        mid = i
        print("MID: " + str(mid))    

    @pyqtSlot(int, name='on_hi_slid_sliderMoved')
    def on_hi_slid_sliderMoved(self, i):    
        hi = i
        print("HI: " + str(hi))    

    @pyqtSlot(int, name='on_treb_slid_sliderMoved')
    def on_treb_slid_sliderMoved(self, i):    
        treb = i
        print("TREB: " + str(treb))    

    @pyqtSlot(int, name='on_lo_freq_slid_sliderMoved')
    def on_lo_freq_slid_sliderMoved(self, i):    
        lo_freq = i
        print("LO_FREQ: " + str(lo_freq))    

    @pyqtSlot(int, name='on_mid_freq_slid_sliderMoved')
    def on_mid_slid_sliderMoved(self, i):    
        mid_freq = i
        print("MID_FREQ: " + str(mid_freq))    

    @pyqtSlot(int, name='on_hi_freq_slid_sliderMoved')
    def on_hi_freq_slid_sliderMoved(self, i):    
        hi_freq = i
        print("HI_FREQ: " + str(hi_freq))    

    @pyqtSlot(int, name='on_input_slid_sliderMoved')
    def on_input_freq_slid_sliderMoved(self, i):    
        inpt = i
        print("INPUT: " + str(inpt))    

    @pyqtSlot(int, name='on_output_slid_sliderMoved')
    def on_output_slid_sliderMoved(self, i):    
        outpt = i
        print("OUTPUT: " + str(outpt))    


##
    @pyqtSlot(int, name='on_input_slid_2_sliderMoved')
    def on_input_slid_2_sliderMoved(self, i):    
        inpt = i
        print("INPUT: " + str(inpt))    

    @pyqtSlot(int, name='on_output_slid_2_sliderMoved')
    def on_output_slid_2_sliderMoved(self, i):    
        outpt = i
        print("INPUT: " + str(outpt))    
##


    @pyqtSlot(int, name='on_cmp_slid1_sliderMoved')
    def on_cmp_slid1_sliderMoved(self, i):    
        cmp_slid1 = i
        print("CMP 1: " + str(cmp_slid1))    

    @pyqtSlot(int, name='on_cmp_slid2_sliderMoved')
    def on_cmp_slid2_sliderMoved(self, i):    
        cmp_slid2 = i
        print("CMP 2: " + str(cmp_slid2))    

    @pyqtSlot(int, name='on_rev_slid1_sliderMoved')
    def on_rev_slid1_sliderMoved(self, i):    
        rev_slid1 = i
        print("REV 1: " + str(rev_slid1))    

    @pyqtSlot(int, name='on_rev_slid2_sliderMoved')
    def on_rev_slid2_sliderMoved(self, i):    
        rev_slid2 = i
        print("REV 2: " + str(rev_slid2))    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()

    # Instantiate client instance
    g = g9Client()

    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()

    # Intantiate thread passing instance of server as argument
    thread = Thread(target = client_thread, args = (g, ui))

    # Begin server thread
    thread.start()

    sys.exit(app.exec_())



    # if __name__ == "__main__":
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # Form = QtWidgets.QWidget()
    # g = g9Client()
    # ui = Ui_Form()
    # ui.setupUi(Form)
    # Form.show()
    # thread = Thread(target = client_thread, args = (g, ui))
    # thread.start()
    

    # sys.exit(app.exec_())